### ISSUE TITLE
Feature request: auto-kick users when they insult slackbutt

### ISSUE THREAD

**Issue by ortizmj12** [Resisty/slackbutt#3]
> John   go fuck yourself, @slackbutt

John should've been auto-kicked for insulting slackbutt. Looks like it's possible: https://api.slack.com/methods/channels.kick

**Comment by Resisty** [comment]
```
user_is_bot 
This method cannot be called by a bot user.
```

#closed #wontfix :C

**Comment by ortizmj12** [comment]
Aww, damn.
