### ISSUE TITLE
"image me" feature similar to hubot's would rock

### ISSUE THREAD

**Issue by ortizmj12** [Resisty/slackbutt#5]
me: hubot image me cheeseburger
hubut: _URL to an image of a cheeseburger_

But in Slack it should embed the image instead of just give the link, right? That'd be cool.

**Comment by Resisty** [comment]
I will do the needful this weekend.

**Comment by Resisty** [comment]
Implemented in a60fac4262f63b52f1bdea3cb79b8a6630b6969d
